Fix init script exit status with VERBOSE=no.

diff --git a/debian/amule-daemon.init b/debian/amule-daemon.init
--- a/debian/amule-daemon.init
+++ b/debian/amule-daemon.init
@@ -39,10 +39,7 @@ do_start()
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --exec $DAEMON --user "$AMULED_USER" --chuid "$AMULED_USER" --test >/dev/null || {
-	    log_progress_msg "(already running)"
-	    return 1
-	}
+	start-stop-daemon --start --quiet --exec $DAEMON --user "$AMULED_USER" --chuid "$AMULED_USER" --test >/dev/null || return 1
 	start-stop-daemon --start --quiet --exec $WRAPPER --user "$AMULED_USER" --chuid "$AMULED_USER" >/dev/null || return 2
 }
 
@@ -62,8 +59,10 @@ case "$1" in
 	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$PROGNAME"
 	do_start
 	case "$?" in
-		0 | 1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2)     [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		1) [ "$VERBOSE" != no ] && \
+			log_progress_msg "(already running)" && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1; exit 1 ;;
 	esac
 	;;
   stop)
@@ -71,7 +70,7 @@ case "$1" in
 	do_stop
 	case "$?" in
 		0 | 1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2)     [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		2)     [ "$VERBOSE" != no ] && log_end_msg 1; exit 1 ;;
 	esac
 	;;
   restart|force-reload)
@@ -82,13 +81,14 @@ case "$1" in
 		do_start
 		case "$?" in
 			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
+			1) log_end_msg 1; exit 1 ;; # Old process is still running
+			*) log_end_msg 1; exit 1 ;; # Failed to start
 		esac
 		;;
 	  *)
 	  	# Failed to stop
 		log_end_msg 1
+		exit 1
 		;;
 	esac
 	;;
@@ -97,3 +97,5 @@ case "$1" in
 	exit 3
 	;;
 esac
+
+exit 0
